package gleifer;

public enum Estado {
	MENU_BOAS_VINDAS,
	MENU_PRINCIPAL,
	MENU_LANCHES,
	MENU_BEBIDAS,
	MENU_ACOMPANHAMENTOS,
	CONFIRMAR_ITEM,
	CARRINHO,
	SOLICITAR_CPF,
	ERRO_CARRINHO_VAZIO,
	VERIFICAR_PONTOS,
	APLICAR_DESCONTO,
	GERAR_PONTOS_PROX_COMPRAS,
	METODO_PAGAMENTO,
	DEBITO_CREDITO,
	EMITIR_TICKET,
	ERRO_CARTAO,
	GERAR_BOLETO,
	CARRINHO_LIMPO,
	CANCELAR_PONTOS_PROX_COMPRAS;
}
